### PR TITLE
Introduced the cache populator service.

### PR DESCRIPTION
**Pull request by garryyao**

### CODE REVIEW

**Comment by mikaelkaron** [comment]
shuld this be pushcache vs. popcache?

**Comment by garryyao** [comment]
I meant for "populate", but I'm ok if you like to rename.

Mikael Karon wrote:

**Comment by garryyao** [comment]
renamed package to `fillcache`

**Comment by garryyao** [comment]
@mikaelkaron is this patch ok?

**Comment by mikaelkaron** [comment]
Quick question. Do we need an additional widget to locate scripts blocks with data? Would it not be enough to just weave the scripts blocks directly by adding `data-weave` directly to the script element. (ps. I still like just plain CacheWidget better than pop/fillcache, thoughts?).

**Comment by garryyao** [comment]
By reading the spec of this service there raise a sequence concern for your suggested approach:

```
Try out all possible ways to populate {@link data.cache.component the cache} in browser environment. This service is generally useful to pre-fill data cache before any {@link data.query.service#event-hub/query} taken place to eliminate the need for network requests.
```

Being the script tags auto woven doesn't give guarantee of it happening before any other services at started (even doesn't guarantee it happens before other widgets). Theoretically this shall be a **service** started right after the cache service.

**Pull request closed without merging**
